@startuml

class IBasedScene {
	+init() : bool
	+create(Args) : IBasedScene
	+createScene(Args) : Scene*
}

class TitleScene {
	+init() : bool
}

class SimulationScene {

}

IBasedScene -- TitleScene
IBasedScene -- SimulationScene

TitleScene -> SimulationScene

@enduml
